version: '3.9'
services:
  finance-bot:
    build: .
    container_name: finance-bot
    restart: always
    env_file:
      - .env
    networks:
      - bot-net

networks:
  bot-net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:dead:beef::/48
